### ISSUE TITLE
Migrate to Spring Boot from servlet

### ISSUE THREAD

**Issue by ebyhr** [yanagishima/yanagishima#184]
Let's begin migration to Spring Boot from servlet so that other people can contribute more easily. 

Migration flow:
1. Introduce Spring core libraries (≠Spring Boot). Use both existing guice and Spring DI
2. Convert servlets to Spring controller

- [x] BookmarkServlet.java
- [x] BookmarkUserServlet.java
- [x] CheckPrestoQueryServlet.java (#237)
- [x] CommentServlet.java (#229)
- [x] ConvertHiveServlet.java
- [x] ConvertPrestoServlet.java
- [x] CsvDownloadServlet.java (#211)
- [x] DatasourceAuthServlet.java (#245)
- [x] DownloadServlet.java
- [x] ElasticsearchQueryStatusServlet.java (#224)
- [x] ElasticsearchServlet.java (#224)
- [x] FormatSqlServlet.java (#206)
- [x] HealthCheckServlet.java
- [x] HistoryServlet.java (#219)
- [x] HistoryStatusServlet.java (#218)
- [x] HiveAsyncServlet.java (#238)
- [x] HivePartitionServlet.java (#241)
- [x] HiveQueryDetailServlet.java (#247)
- [x] HiveQueryStatusServlet.java (#246)
- [x] HiveServlet.java (#238)
- [x] KillHiveServlet.java (#242)
- [x] LabelServlet.java (#252)
- [x] PrestoAsyncServlet.java (#226)
- [x] PrestoKillServlet.java (#228)
- [x] PrestoPartitionServlet.java (#235)
- [x] PrestoServlet.java (#236)
- [x] PublishServlet.java
- [x] QueryDetailServlet.java
- [x] QueryHistoryServlet.java (#251)
- [x] QueryHistoryUserServlet.java (#253)
- [x] QueryServlet.java (#239)
- [x] QueryStatusServlet.java (#244)
- [x] ShareCsvDownloadServlet.java (#212)
- [x] ShareDownloadServlet.java
- [x] ShareHistoryServlet.java (#219)
- [x] SparkJobListServlet.java (#248)
- [x] StarredSchemaServlet.java (#222)
- [x] YarnJobListServlet.java (#249)

3. Extract service and repository from controller (remove TinyORM)
- [x] Bookmark
- [x] Comment (#254)
- [x] Label (deprecated #262)
- [x] Publish (#230)
- [x] Query
- [x] QueryV14 (deprecated #264)
- [x] SessionProperty (#256)
- [x] StarredSchema

4. Replace guice with Spring DI and migrate to Spring Boot

**Comment by wyukawa** [comment]
First of all, basically I agree with migration from guice + servlet to sping boot.

On the other hand, the current biggest issue in yanagishima api server is https://github.com/yanagishima/yanagishima/issues/63

We need to restart yanagishima every 8 hours due to this issue.

I guess this issue comes from my poor handling guice and tinyorm.

I tried to introduce `HealthCheckServlet` to avoid this issue but failed.

I hope this issue will be resolved if you try to introduce spring boot.

You can remove `ToValuesQueryServlet` and  `TableListServlet` because we don't use now.

`CheckPrestoQueryServlet` and `HealthCheckServlet` are not also used now but we might use in the future.

You can replace or remove these servlets if you like.

Aside from servlets, we can remove `OldPrestoService` and `OldPrestoServiceImpl` because we don't use old presto.

**Comment by ebyhr** [comment]
Though we can fix the issue easily after the migration, that will take some time. Let's fix in #186.
